version: '3'

services:
  elasticsearch:
    restart: always
    image: amazon/opendistro-for-elasticsearch:1.6.0
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
    expose:
      - "9200"
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    restart: always
    image: amazon/opendistro-for-elasticsearch-kibana:1.6.0
    hostname: kibana
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
      ELASTICSEARCH_HOSTS: https://elasticsearch:9200
  rabbitmq:
    restart: always
    image: rabbitmq:3-management
    hostname: rabbit
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbit_data:/var/lib/rabbitmq
  analyze_image:
    image: analyze_image
    hostname: analyze_image
    build: ./analyze_image
    ports:
      - 1490:1490
  analyze_text:
    image: analyze_text
    hostname: analyze_text
    build: ./analyze_text
    ports:
      - 1491:1491


volumes:
  rabbit_data:
    driver: local
  esdata:
    driver: local
